import React from 'react';
import Image from 'next/image';

export default function TextDetector() {
  return (
    <div className="min-h-screen flex items-center justify-center bg-black text-white">
      <div className="flex gap-32">
        <div className="w-[60vh] h-[58vh] bg-[#2F2F31] rounded-lg flex items-center justify-center shadow-lg border-2 border-gray-700">
          <p className="text-lg ml-3 mt-[-52px] px-4">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum congue porta tristique. Proin dignissim augue neque, sit amet posuere eros consectetur eu. Donec vel tellus sodales ipsum ultrices suscipit ac vitae odio. Nulla imperdiet venenatis orci, mattis euismod mi iaculis quis. In hac habitasse platea dictumst. Sed molestie leo in consectetur molestie. Praesent neque felis, imperdiet in tortor ac, ornare molestie eros. Morbi laoreet mi non lorem maximus, ac porttitor nunc consectetur. Donec egestas vestibulum feugiat. Aliquam auctor lacus eget maximus venenatis. Pellentesque ac mi euismod quam congue tristique non nec sapie
          </p>
        </div>

        <div className="flex flex-col items-center">
          <div className="w-[40vh] h-[24vh] bg-[#11140D] rounded-[4px] flex flex-col items-center justify-center shadow-lg">
            <Image 
              src="/ok.webp" 
              alt="Description of image" 
              width={100} 
              height={80} 
              className="rounded-md"
            />
            <p className="mt-2 text-lg text-[#21791F] font-bold">This seems legit</p>
          </div>
          <p className="mt-12 text-2xl font-medium text-center">
            12% chance of being AI generated
          </p>
          <p className="mt-8 text-2xl font-medium text-center">
            This is very unlikely to be <br /> generated by AI
          </p>

          <button className="mt-6 bg-[#0600C2] hover:bg-green-700 text-white font-bold py-2 px-6 rounded-xl transition-all text-2xl">
            Detect More
          </button>
        </div>
      </div>
    </div>
  );
}
